_target_: pytorch_lightning.Trainer

defaults:
  - override /trainer: minimal.yaml

# override: trainer
gpus: 1
amp_backend: apex
precision: 16
amp_level: "O2"

min_epochs: 1
max_epochs: 10
data_dir: ${work_dir}/../data/musdb18_dev_wav

# prints
progress_bar_refresh_rate: null
weights_summary: null
profiler: null

# debugs
num_sanity_val_steps: 2
fast_dev_run: False
overfit_batches: 0
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
track_grad_norm: -1
terminate_on_nan: False
