_target_: pytorch_lightning.Trainer

defaults:
  - minimal.yaml # choose trainer from 'configs/trainer/'

deterministic: True

gpus: 4
accelerator: ddp
amp_backend: "native"
precision: 16
amp_level: "O2"