# @package _global_

# to execute this experiment run:
# python run.py experiment=example_simple.yaml

defaults:
  - multigpu_default.yaml

# Training Environment
target_name: vocals
batch_size: 4
gpus: 2
sync_batchnorm: True
lr: 0.0001
check_val_every_n_epoch: 10
seed: 2020

# STFT
dim_f: 2048
dim_t: 256
dim_c: 4
hop_length: 1024

# data augmentation
external_datasets:
augmentation: True

model:
  # model configuration
  num_blocks: 11
  l: 3 # temporal
  g: 32 # temporal
  k: 3
  bn: 8
  bias: False

