# @package _global_

# to execute this experiment run:
# python run.py experiment=example_simple.yaml

defaults:
  - final_vocals.yaml
  - override /logger: tensorboard.yaml
  - override /callbacks: none.yaml

trainer:
  max_epochs: 15
  check_val_every_n_epoch: 14
