# @package _global_

# to execute this experiment run:
# python run.py experiment=example_simple.yaml

defaults:
  - multigpu_default

# Training Environment
target_name: drums
batch_size: 4
gpus: 4
lr: 0.0003
num_workers: 0 # num of cpus
pin_memory: False # True then faster

# STFT
n_fft: 4096
dim_f: 2048
dim_t: 128
dim_c: 4
hop_length: 1024

# data augmentation
external_datasets:
augmentation: True

model:
  # model configuration
  num_blocks: 9
  l: 5
  g: 32
  k: 3
  bn:
  bias: