# @package _global_

# to execute this experiment run:
# python run.py experiment=example_simple.yaml

defaults:
  - multigpu_default.yaml

target_name: vocals
batch_size: 10
gpus: 4
check_val_every_n_epoch: 10
lr: 0.00034702
sync_batchnorm: True
seed: 2021
