model:
  # model
  _target_: src.models.mdxnet.ConvTDFNet
  target_name: ${target_name}

  # model configuration
  num_blocks: 9
  l: 5
  g: 32
  k: 3
  bn: 8
  bias: False

  # optimizer
  lr: 0.0001
  optimizer: rmsprop

  # stft
  n_fft: 6144
  dim_f: 256
  dim_t: 128
  dim_c: 4
  hop_length: 1024

##########################

sources:
  - 'vocals'


vocals:
  # model configuration
  _target_: src.models.mdxnet.ConvTDFNet
  target_name: vocals

  # model configuration
  num_blocks: 5
  l: 5
  g: 32
  k: 3
  bn: 8
  bias: False

  # optimizer
  lr: 0.0001
  optimizer: rmsprop

  # stft
  n_fft: 6144
  dim_f: 2048
  dim_t: 128
  dim_c: 4
  hop_length: 1024

gpus: 1