#model:
#  # model
#  _target_: src.models.mdxnet.ConvTDFNet
#  target_name: ${target_name}
#
#  # model configuration
#  num_blocks: 9
#  l: 5
#  g: 32
#  k: 3
#  bn: 8
#  bias: False
#
#  # optimizer
#  lr: 0.0001
#  optimizer: rmsprop
#
#  # stft
#  n_fft: 6144
#  dim_f: 256
#  dim_t: 128
#  dim_c: 4
#  hop_length: 1024

##########################

sources:
  - 'drums'

drums:
  # model
  _target_: src.models.mdxnet.ConvTDFNet
  target_name: drums
  ckpt_path: 'logs/runs/drums/2021-08-02/02-34-12/checkpoints/epoch=189.ckpt'

  # model configuration
  num_blocks: 11
  l: 3
  g: 32
  k: 3
  bn: 8
  bias: False

  # optimizer
  lr: 0.0001
  optimizer: rmsprop

  # stft
  n_fft: 4096
  dim_f: 2048
  dim_t: 256
  dim_c: 4
  hop_length: 1024
