_target_: src.models.mdxnet.ConvTDFNet

target_name: 'drums'

# model
num_blocks: 9
l: 3
g: 32
k: 3
bn: 8
bias: False

# stft
n_fft: 4096
dim_f: 2048
dim_t: 128
dim_c: 4
hop_length: 1024

# optimizer
lr: 0.0002
optimizer: rmsprop