_target_: src.models.mdxnet.ConvTDFNet

target_name: ${datamodule.target_name}

lr: 0.0003
optimizer: rmsprop

num_blocks: 9
l: 5
g: 32
k: 3
dim_f: ${dim_f}
dim_t: ${dim_t}
n_fft: ${n_fft}
hop_length: ${hop_length}
bn:
bias: # deprecated

