_target_: src.models.mdxnet.Mixer

target_name: 'all'

model_cfg_dir: '/home/ielab/PycharmProjects/mdx-net/configs/model/'
separator_configs:
  - ConvTDFNet_other.yaml
  - ConvTDFNet_other.yaml
  - ConvTDFNet_other.yaml
  - ConvTDFNet_other.yaml

dim_t: 256
hop_length: 1024

# optimizer
lr: 0.003
optimizer: rmsprop