# @package _global_

# specify here default training configuration
defaults:
  - datamodule: dummy.yaml
  - eval_config: default.yaml
  - logger: wandb.yaml
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

# dummy
target_name: vocals
work_dir: ${hydra:runtime.cwd}
# dummy

# default
data_dir: ${oc.env:data_dir}
onnx_dir: ${oc.env:onnx_dir}

split: 'valid'

wandb_api_key: ${oc.env:wandb_api_key}

batch_size: 8

logger:
  wandb:
    project: mdx_eval_${split}