# @package _global_

# specify here default training configuration
defaults:
  - model: ConvTDFNet_drums
  - logger: wandb.yaml
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

ckpt_path: 'drums/2021-08-02/02-34-12/checkpoints/epoch=169.ckpt'

split: 'valid'
batch_size: 8
device: 'cuda:3'

data_dir: ${oc.env:data_dir}
ckpt_dir: ${oc.env:ckpt_dir}
wandb_api_key: ${oc.env:wandb_api_key}

logger:
  wandb:
    project: mdx_eval_${split}
    name: ${ckpt_path}