_target_: src.datamodules.musdb18hq_datamodule.Musdb18hqDataModule

defaults:
  - musdb18_hq

target_name: 'vocals'
n_fft: 4096
hop_length: 1024
dim_c: 4
dim_f: 2048
dim_t: 256

num_workers: 0
pin_memory: False

external_datasets:
aug_params: