_target_: src.datamodules.musdb18hq_datamodule.Musdb18hqDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
target_name: # <- No default! Mandatory!
n_fft: ${n_fft}
hop_length: ${hop_length}
dim_c: ${dim_c}
dim_f: ${dim_f}
dim_t: ${dim_t}
sampling_rate: 44100

batch_size: 8
num_workers: 0
pin_memory: False

validation_set:
  - Actions - One Minute Smile
  - Clara Berry And Wooldog - Waltz For My Victims
  - Johnny Lokke - Promises & Lies
  - Patrick Talbot - A Reason To Leave
  - Triviul - Angelsaint
  - Alexander Ross - Goodbye Bolero
  - Fergessen - Nos Palpitants
  - Leaf - Summerghost
  - Skelpolu - Human Mistakes
  - Young Griffo - Pennies
  - ANiMAL - Rockshow
  - James May - On The Line
  - Meaxic - Take A Step
  - Traffic Experiment - Sirens