_target_: src.datamodules.musdb18hq_datamodule.Musdb18hqDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
sampling_rate: 44100

target_name: ${model.target_name}
n_fft: ${model.n_fft}
hop_length: ${model.hop_length}
dim_c: ${model.dim_c}
dim_f: ${model.dim_f}
dim_t: ${model.dim_t}

batch_size: 8
num_workers: 0
pin_memory: False

external_datasets:
aug_params:
  - 2
  - 20

validation_set:
  - Actions - One Minute Smile
  - Clara Berry And Wooldog - Waltz For My Victims
  - Johnny Lokke - Promises & Lies
  - Patrick Talbot - A Reason To Leave
  - Triviul - Angelsaint
  - Alexander Ross - Goodbye Bolero
  - Fergessen - Nos Palpitants
  - Leaf - Summerghost
  - Skelpolu - Human Mistakes
  - Young Griffo - Pennies
  - ANiMAL - Rockshow
  - James May - On The Line
  - Meaxic - Take A Step
  - Traffic Experiment - Sirens